### PR TITLE
readme stats fix

### PR DESCRIPTION
**Pull request by fhrrrzy**
fixing parameter request to github readme stats api.

### CODE REVIEW

**Comment by fhrrrzy** [comment]
just passing by to a dicoding fellow GitHub profile and noticed something wrong with the stats on it, hope you accept the PR, and have a great day!

**Comment by intansduano** [comment]
Thank you so much Fahrurozi! Have a great day :)

**Review by intansduano — COMMENTED** [review]
Thanks a lot! I'm a newbie haha

**Comment by fhrrrzy** [comment]
hope we can learn together in near future :>

**Comment by intansduano** [comment]
Yeah, for sure :D

**Pull request merged**
